Repository InfyOmLabs/infy-tracker, pull requests merged in 2019-09, with the labels that each got.

#305 sample commit for permission test
  database/factories/UserFactory.php
  tests/Permissiion/RoleControllerPermissionTest.php
  tests/TestCase.php
Labels: approved-by-vishal, ready-for-review

#301 Monika/first focus 66
  resources/assets/js/custom.js
  resources/assets/js/report/report.js
  resources/assets/js/users/user.js
Labels: ready-for-review

#304 feat(time-entry): when user open new time entry pop up end will be se…
  resources/assets/js/time_entries/time_entry.js
Labels: ready-for-review

#311 fix(task-detail): remove file when multiple file upload using dropzon
  resources/assets/js/task/task_detail.js
Labels: ready-for-review

#312 fix(edit-profile): added password view/block functionality
  resources/assets/js/profile/profile.js
  resources/assets/style/sass/style.scss
  resources/views/profile/edit_profile.blade.php
Labels: ready-for-review

#302 Monika/role field required
  app/Http/Requests/UpdateUserRequest.php
  app/Models/User.php
  resources/views/users/modal.blade.php
  tests/Controllers/Validations/UserControllerValidationTest.php
Labels: ready-for-review

#308 fix(UI): remove pagination icons if there is only one page in datatab…
  resources/assets/js/custom.js
Labels: ready-for-review

#307 feat(time-entry): if time entry geater than 12 hr then allow user to …
  resources/assets/js/time_tracker/time_tracker.js
  resources/views/layouts/app.blade.php
  resources/views/time_entries/index.blade.php
  resources/views/time_tracker/adjust_time_entry.blade.php
Labels: ready-for-review

#320 feat(dashboard): remove unused projects from custom report in dashboard
  resources/assets/js/dashboard/dashboard.js
  resources/assets/js/dashboard/developers-daily-report.js
  resources/assets/js/time_entries/time_entry.js
  resources/views/dashboard/index.blade.php
Labels: ready-for-review

#310 test cases for tag permission controller test
  tests/Permissiion/TagControllerPermissionTest.php
Labels: approved-by-vishal, ready-for-review

#314 test cases for client permissions
  tests/Permissiion/ClientControllerPermissionTest.php
Labels: approved-by-vishal, ready-for-review

#315 test cases for project permission test
  tests/Permissiion/ProjectControllerPermissionTest.php
Labels: approved-by-vishal, ready-for-review

#316 test cases for activity type controller permission
  tests/Permissiion/ActivityTypeControllerPermissionTest.php
Labels: approved-by-vishal, ready-for-review

#317 test cases for user permission test
  tests/Permissiion/UserControllerPermissionTest.php
Labels: ready-for-review

#318 1) test cases for task permission
  database/factories/TaskFactory.php
  tests/Permissiion/TaskControllerPermissionTest.php
Labels: ready-for-review

#319 test cases for task API permission
  database/factories/TaskFactory.php
  tests/Controllers/TaskControllerTest.php
  tests/Permissiion/TaskControllerPermissionTest.php
Labels: ready-for-review

#313 test cases for report permission
  database/factories/ReportFactory.php
  tests/Permissiion/ReportControllerPermissionTest.php
Labels: approved-by-vishal, ready-for-review

#321 feat(dashboard): chnage date formate
  app/Repositories/DashboardRepository.php
  tests/Repositories/DashboardRepositoryTest.php
Labels: ready-for-review

#322 fix(task-detail): try to fix task-detail pop up collaps row issue
  resources/assets/js/task/task.js
Labels: ready-for-review

#323 feat(report): added task link in report view screen
  app/Repositories/ReportRepository.php
  resources/views/reports/report_format.blade.php
Labels: ready-for-review

#325 test cases for validate user
  tests/Controllers/Validations/UserControllerValidationTest.php
Labels: ready-for-review

#330 Release v1.8.2-alpha
  app/Http/Requests/UpdateUserRequest.php
  app/Models/User.php
  app/Repositories/DashboardRepository.php
  app/Repositories/ReportRepository.php
  composer.json
  database/factories/ReportFactory.php
  database/factories/TaskFactory.php
  database/factories/UserFactory.php
  resources/assets/js/custom.js
  resources/assets/js/dashboard/dashboard.js
  resources/assets/js/dashboard/developers-daily-report.js
  resources/assets/js/profile/profile.js
  resources/assets/js/report/report.js
  resources/assets/js/task/task.js
  resources/assets/js/task/task_detail.js
  resources/assets/js/time_entries/time_entry.js
  resources/assets/js/time_tracker/time_tracker.js
  resources/assets/js/users/user.js
  resources/assets/style/sass/style.scss
  resources/views/dashboard/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/profile/edit_profile.blade.php
  resources/views/reports/report_format.blade.php
  resources/views/roles/create.blade.php
  resources/views/roles/edit.blade.php
  resources/views/time_entries/index.blade.php
  resources/views/time_tracker/adjust_time_entry.blade.php
  resources/views/users/modal.blade.php
  tests/Controllers/TaskControllerTest.php
  tests/Controllers/Validations/UserControllerValidationTest.php
  tests/Permissiion/ActivityTypeControllerPermissionTest.php
  tests/Permissiion/ClientControllerPermissionTest.php
  tests/Permissiion/ProjectControllerPermissionTest.php
  tests/Permissiion/ReportControllerPermissionTest.php
  tests/Permissiion/RoleControllerPermissionTest.php
  tests/Permissiion/TagControllerPermissionTest.php
  tests/Permissiion/TaskControllerPermissionTest.php
  tests/Permissiion/UserControllerPermissionTest.php
  tests/Repositories/DashboardRepositoryTest.php
  tests/TestCase.php
Labels: ready-for-review

#324 fix(UI): solve console warning
  resources/assets/js/task/task.js
  resources/assets/js/task/task_detail.js
  resources/views/clients/edit_modal.blade.php
  resources/views/clients/modal.blade.php
  resources/views/tags/edit_modal.blade.php
  resources/views/tags/modal.blade.php
  resources/views/tasks/edit_modal.blade.php
  resources/views/tasks/modal.blade.php
  resources/views/time_entries/modal.blade.php
  resources/views/users/edit_modal.blade.php
  resources/views/users/modal.blade.php
Labels: ready-for-review

#326 fix(task-detail): solve edit task error in task detail page
  resources/assets/js/task/task_detail.js
Labels: ready-for-review

#327 fix(roles): improve role add edit ui
  resources/views/roles/edit_fields.blade.php
  resources/views/roles/fields.blade.php
Labels: ready-for-review

#328 feat(report): added time entry detail pop up on click of task header …
  app/Repositories/ReportRepository.php
  resources/assets/js/task/task.js
  resources/assets/js/task/task_time_entry.js
  resources/assets/style/sass/report.scss
  resources/views/reports/report_format.blade.php
  resources/views/reports/show.blade.php
  resources/views/tasks/index.blade.php
  resources/views/tasks/time_tracking_modal.blade.php
  webpack.mix.js
Labels: ready-for-review

#331 feat(user-profile): changed user-avtar image to user name image
  app/Models/User.php
  resources/views/dashboard/index.blade.php
Labels: ready-for-review

#334 Monika/align heading
  resources/assets/style/sass/style.scss
  resources/views/activity_types/index.blade.php
  resources/views/clients/index.blade.php
  resources/views/projects/index.blade.php
  resources/views/reports/create.blade.php
  resources/views/reports/edit.blade.php
  resources/views/reports/index.blade.php
  resources/views/reports/show.blade.php
  resources/views/roles/index.blade.php
  resources/views/tags/index.blade.php
  resources/views/tasks/index.blade.php
  resources/views/tasks/show.blade.php
  resources/views/time_entries/index.blade.php
  resources/views/users/index.blade.php
Labels: ready-for-review

#332 Monika/deleted by
  app/Http/Controllers/ActivityTypeController.php
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/TagController.php
  app/Http/Controllers/UserController.php
  app/Models/ActivityType.php
  app/Models/Client.php
  app/Models/Project.php
  app/Models/Tag.php
  app/Models/Task.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_05_02_101439_create_activity_types_table.php
  database/migrations/2019_05_02_101619_create_clients_table.php
  database/migrations/2019_05_03_043336_create_tags_table.php
  database/migrations/2019_05_03_050601_create_projects_table.php
  database/migrations/2019_05_03_060503_create_tasks_table.php
  database/migrations/2019_05_03_072634_create_task_tags_table.php
  database/migrations/2019_05_03_094616_create_time_entries_table.php
  database/migrations/2019_05_22_115729_create_table_task_assignees.php
  database/migrations/2019_06_11_062240_create_project_users_table.php
  database/migrations/2019_06_18_093135_create_table_task_attachment.php
  database/migrations/2019_07_01_050129_entrust_setup_tables.php
  database/migrations/2019_07_06_121218_create_reports_table.php
  database/migrations/2019_09_05_123722_add_soft_delete_in_all_table.php
  database/testing.sqlite
  resources/assets/js/projects/project.js
  resources/assets/js/time_entries/time_entry.js
Labels: ready-for-review

#335 feat(time-entry): reduce width of time entry detail pop up in task de…
  resources/views/tasks/time_tracking_modal.blade.php
Labels: ready-for-review

#337 fix(dashboard): place calendar on right corner in dashboard if user d…
  resources/views/dashboard/index.blade.php
Labels: ready-for-review

#338 fix(time-entry): solve time entry project filter for admin
  app/Queries/TimeEntryDataTable.php
Labels: ready-for-review

#339 feat(activity-type): added validation for activity delete and write i…
  app/Http/Controllers/ActivityTypeController.php
  app/Models/ActivityType.php
  tests/Controllers/ActivityTypeControllerTest.php
Labels: approved-by-vishal, ready-for-review

#341 Monika/input delete
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ProjectController.php
  app/Models/Client.php
  app/Models/Project.php
  app/Models/Task.php
  app/Repositories/ClientRepository.php
  app/Repositories/ProjectRepository.php
  public/images/warning.png
  resources/assets/js/clients/client.js
  resources/assets/js/custom.js
  resources/assets/js/projects/project.js
  resources/assets/style/sass/style.scss
  tests/Controllers/ClientControllerTest.php
  tests/Controllers/ProjectControllerTest.php
Labels: ready-for-review

#343 feat(search): added search support in filter dropdown in project, ta…
  resources/assets/js/projects/project.js
  resources/assets/js/task/task.js
  resources/assets/js/time_entries/time_entry.js
Labels: ready-for-review

#346 add doc for deleted by property
  app/Models/ActivityType.php
  app/Models/Client.php
  app/Models/Project.php
  app/Models/Tag.php
  app/Models/User.php
Labels: ready-for-review

#349 test case for time entry
  tests/Controllers/TimeEntryControllerTest.php
Labels: approved-by-vishal, ready-for-review, test

#351 test cases for latest merged API code
  app/Repositories/ClientRepository.php
  app/Repositories/ProjectRepository.php
  tests/Controllers/ClientControllerTest.php
  tests/Controllers/ProjectControllerTest.php
  tests/Repositories/ClientRepositoryTest.php
  tests/Repositories/ProjectRepositoryTest.php
Labels: ready-for-review, test

#353 fix(time-entry): in time entry table - formatted duration 00:00h, not…
  resources/assets/js/custom.js
  resources/assets/js/task/task.js
  resources/assets/js/task/task_time_entry.js
  resources/assets/js/time_entries/time_entry.js
  resources/views/tasks/time_tracking_modal.blade.php
  resources/views/time_entries/table.blade.php
Labels: ready-for-review

#348 feat(profile): Hidden icon for passwords on profile screen
  resources/assets/js/profile/profile.js
  resources/assets/style/sass/style.scss
  resources/views/profile/edit_profile.blade.php
Labels: ready-for-review

#352 fix(report): in time entry pop up time entry will come between report…
  app/Repositories/TaskRepository.php
  resources/assets/js/task/task.js
  resources/assets/js/task/task_time_entry.js
  resources/views/reports/create.blade.php
  resources/views/reports/edit.blade.php
  resources/views/reports/show.blade.php
  resources/views/tasks/index.blade.php
Labels: ready-for-review

#350 fix(modal): fix allignment issue in modal
  resources/assets/style/sass/style.scss
Labels: ready-for-review

#354 fix(UI): added first focus for input fields only
  resources/assets/js/custom.js
  resources/views/tasks/edit_modal.blade.php
  resources/views/tasks/modal.blade.php
  resources/views/time_entries/edit_modal.blade.php
  resources/views/time_entries/modal.blade.php
Labels: ready-for-review

#340 test cases for helper
  tests/Unit/Helpers/HelpersTest.php
Labels: ready-for-review, test

#361 refactor task status
  app/Http/Controllers/TaskController.php
  database/factories/TaskFactory.php
  database/migrations/2019_09_13_054205_update_task_status_field_value.php
  tests/Controllers/TaskControllerTest.php
  tests/Controllers/TimeEntryControllerTest.php
  tests/Controllers/Validations/TaskControllerValidationTest.php
  tests/Repositories/TaskRepositoryTest.php
  tests/Repositories/TimeEntryRepositoryTest.php
Labels: approved-by-vishal, ready-for-review

#365 refactor modal code
  app/Models/Comment.php
  app/Models/Report.php
  app/Models/Task.php
  app/Models/TaskAttachment.php
Labels: approved-by-vishal, ready-for-review

#367 refactor data table code
  app/Queries/ActivityTypeDataTable.php
  app/Queries/RoleDataTable.php
  app/Queries/TaskDataTable.php
Labels: approved-by-vishal, ready-for-review

#369 refactor repository code
  app/Models/Task.php
  app/Repositories/AccountRepository.php
  app/Repositories/ActivityTypeRepository.php
  app/Repositories/ClientRepository.php
  app/Repositories/PermissionRepository.php
  app/Repositories/ProjectRepository.php
  app/Repositories/TagRepository.php
  app/Repositories/TimeEntryRepository.php
  app/Repositories/UserRepository.php
Labels: ready-for-review

#364 refactor task test cases
  tests/Controllers/Validations/TimeEntryControllerValidationTest.php
  tests/Repositories/TaskRepositoryTest.php
  tests/Repositories/TimeEntryRepositoryTest.php
Labels: ready-for-review, test

#371 refactor controller code
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/TaskController.php
  app/Http/Controllers/TimeEntryController.php
  app/Http/Controllers/UserController.php
  app/helpers.php
Labels: ready-for-review

#362 Query refactored
  app/Repositories/TaskRepository.php
Labels: ready-for-review

#373 Search should be worked on task and time entry
  app/Http/Controllers/TaskController.php
Labels: ready-for-review

#374 fix(task_detail): added project relation in task detail
  app/Repositories/TaskRepository.php
Labels: ready-for-review

#376 Release v1.8.5-alpha
  app/Http/Controllers/TaskController.php
  app/Repositories/TaskRepository.php
  composer.json
Labels: ready-for-review

#377 fix search issue in time-entries
  resources/assets/js/time_entries/time_entry.js
Labels: ready-for-review

#383 refactor(migrations): added soft delete migrations in create migrations
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_05_02_101439_create_activity_types_table.php
  database/migrations/2019_05_02_101619_create_clients_table.php
  database/migrations/2019_05_03_043336_create_tags_table.php
  database/migrations/2019_05_03_050601_create_projects_table.php
  database/migrations/2019_09_05_123722_add_soft_delete_in_all_table.php
Labels: ready-for-review

#389 fix(migrations): refactor all migrations
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_05_03_050601_create_projects_table.php
  database/migrations/2019_05_03_060503_create_tasks_table.php
  database/migrations/2019_05_03_094616_create_time_entries_table.php
  database/migrations/2019_06_17_112629_add_image_path_column_to_users_table.php
  database/migrations/2019_06_20_120323_add_prefix_column_into_projects_table.php
  database/migrations/2019_06_21_100058_add_task_number_column_to_tasks_table.php
  database/migrations/2019_06_21_113319_add_prefix_value_to_exist_record_in_project.php
  database/migrations/2019_06_21_115135_add_unique_constraints_to_prefix_column_of_projects.php
  database/migrations/2019_06_21_120121_migrate_value_of_task_number_in_tasks_table.php
  database/migrations/2019_06_22_050515_add_priority_column_to_tasks_table.php
  database/migrations/2019_06_22_050643_add_unique_constraints_to_task_number_column_of_tasks.php
  database/migrations/2019_06_27_100143_update_priority_to_exist_records_in_task_table.php
  database/migrations/2019_07_01_050129_entrust_setup_tables.php
  database/migrations/2019_08_21_125409_add_entry_type_in_time_entries_table.php
  database/migrations/2019_09_13_054205_update_task_status_field_value.php
  database/migrations/2019_09_14_060036_backup_entrust_tables.php
  database/migrations/2019_09_17_042742_add_default_permissions_and_roles.php
Labels: ready-for-review

#390 Monika/task detail
  app/Models/Comment.php
  resources/assets/js/task/task_detail.js
  resources/assets/style/sass/_variables.scss
  resources/assets/style/sass/task-detail.scss
  resources/views/tasks/show.blade.php
Labels: ready-for-review

#391 Monika/task detail
  app/Models/Comment.php
  resources/assets/js/task/task_detail.js
  resources/assets/style/sass/_variables.scss
  resources/assets/style/sass/task-detail.scss
  resources/views/tasks/show.blade.php
Labels: ready-for-review

#380 Monika/upgrade laravel 6
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/TimeEntryController.php
  app/Http/Kernel.php
  app/Models/Comment.php
  app/Models/Permission.php
  app/Models/Role.php
  app/Models/User.php
  app/Queries/TimeEntryDataTable.php
  composer.json
  composer.lock
  config/app.php
  config/permission.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_05_03_050601_create_projects_table.php
  database/migrations/2019_05_03_060503_create_tasks_table.php
  database/migrations/2019_05_03_094616_create_time_entries_table.php
  database/migrations/2019_06_17_112629_add_image_path_column_to_users_table.php
  database/migrations/2019_06_20_120323_add_prefix_column_into_projects_table.php
  database/migrations/2019_06_21_100058_add_task_number_column_to_tasks_table.php
  database/migrations/2019_06_21_113319_add_prefix_value_to_exist_record_in_project.php
  database/migrations/2019_06_21_115135_add_unique_constraints_to_prefix_column_of_projects.php
  database/migrations/2019_06_21_120121_migrate_value_of_task_number_in_tasks_table.php
  database/migrations/2019_06_22_050515_add_priority_column_to_tasks_table.php
  database/migrations/2019_06_22_050643_add_unique_constraints_to_task_number_column_of_tasks.php
  database/migrations/2019_06_27_100143_update_priority_to_exist_records_in_task_table.php
  database/migrations/2019_07_01_050129_entrust_setup_tables.php
  database/migrations/2019_08_21_125409_add_entry_type_in_time_entries_table.php
  database/migrations/2019_09_13_054205_update_task_status_field_value.php
  database/migrations/2019_09_14_060733_create_permission_tables.php
  database/seeds/AssignDefaultRoleToUserSeeder.php
  database/seeds/DefaultRoleSeeder.php
  database/testing.sqlite
  resources/assets/js/custom.js
  resources/assets/js/task/task_detail.js
  resources/assets/js/task/task_time_entry.js
  resources/assets/js/time_entries/time_entry.js
  resources/assets/style/sass/_variables.scss
  resources/assets/style/sass/task-detail.scss
  resources/views/dashboard/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/menu.blade.php
  resources/views/roles/edit_fields.blade.php
  resources/views/tasks/show.blade.php
  resources/views/time_entries/index.blade.php
  routes/web.php
  tests/Repositories/RoleRepositoryTest.php
  tests/TestCase.php
Labels: approved-by-vishal, ready-for-review

#394 remove times(unused) code
  database/factories/TaskFactory.php
  tests/Controllers/TaskControllerTest.php
  tests/Repositories/ActivityTypeRepositoryTest.php
  tests/Repositories/ClientRepositoryTest.php
  tests/Repositories/ProjectRepositoryTest.php
  tests/Repositories/ReportRepositoryTest.php
  tests/Repositories/RoleRepositoryTest.php
  tests/Repositories/TagRepositoryTest.php
  tests/Repositories/TaskRepositoryTest.php
  tests/Repositories/UserRepositoryTest.php
Labels: ready-for-review

#392 generate test cases doc
  tests/Controllers/ActivityTypeControllerTest.php
  tests/Controllers/Auth/LoginControllerTest.php
  tests/Controllers/CommentControllerTest.php
  tests/Controllers/HomeControllerTest.php
  tests/Controllers/ProjectControllerTest.php
  tests/Controllers/ReportControllerTest.php
  tests/Controllers/RoleControllerTest.php
  tests/Controllers/TagControllerTest.php
  tests/Controllers/TimeEntryControllerTest.php
  tests/Controllers/UserControllerTest.php
  tests/Controllers/Validations/ActivityTypeControllerValidationTest.php
  tests/Controllers/Validations/TagControllerValidationTest.php
  tests/Controllers/Validations/TaskControllerValidationTest.php
  tests/Controllers/Validations/TimeEntryControllerValidationTest.php
  tests/Models/ProjectTest.php
  tests/Models/ReportFilterTest.php
  tests/Models/TaskTest.php
  tests/Models/TimeEntryTest.php
  tests/Permissions/ActivityTypeControllerPermissionTest.php
  tests/Permissions/ClientControllerPermissionTest.php
  tests/Permissions/ProjectControllerPermissionTest.php
  tests/Permissions/ReportControllerPermissionTest.php
  tests/Permissions/RoleControllerPermissionTest.php
  tests/Permissions/TagControllerPermissionTest.php
  tests/Permissions/TaskControllerPermissionTest.php
  tests/Permissions/UserControllerPermissionTest.php
  tests/Repositories/ActivityTypeRepositoryTest.php
  tests/Repositories/DashboardRepositoryTest.php
  tests/Repositories/TagRepositoryTest.php
  tests/Unit/Helpers/HelpersTest.php
Labels: ready-for-review

#387 2) refactor modal code
  app/Models/ActivityType.php
  app/Models/Client.php
  app/Models/Comment.php
  app/Models/Project.php
  app/Models/Report.php
  app/Models/Tag.php
  app/Models/Task.php
  app/Models/TimeEntry.php
  app/Models/User.php
Labels: ready-for-review

#385 1) refactor code
  app/Events/AddComment.php
  app/Events/DeleteComment.php
  app/Events/StartTimer.php
  app/Events/StopWatchStop.php
  app/Events/UpdateComment.php
  app/Http/Controllers/TaskController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/CheckUserIsActivated.php
  app/Http/Middleware/ValidateUserMiddleware.php
Labels: ready-for-review

#388 refactor repo code
  app/Queries/ProjectDataTable.php
  app/Queries/TimeEntryDataTable.php
  app/Queries/UserDataTable.php
  tests/Controllers/ProjectControllerTest.php
  tests/Controllers/TaskControllerTest.php
  tests/Controllers/TimeEntryControllerTest.php
  tests/Repositories/ClientRepositoryTest.php
  tests/Repositories/ProjectRepositoryTest.php
  tests/Repositories/ReportRepositoryTest.php
  tests/Repositories/TaskRepositoryTest.php
  tests/Repositories/UserRepositoryTest.php
Labels: ready-for-review

#375 fix and add task test cases
  tests/Repositories/TaskRepositoryTest.php
Labels: ready-for-review, test

#397 test cases for report attribute
  tests/Models/CommentTest.php
  tests/Models/ReportTest.php
Labels: ready-for-review

#398 test cases for modal attributes
  app/Models/TimeEntry.php
  tests/Models/TaskAttachmentTest.php
  tests/Models/TaskTest.php
  tests/Models/TimeEntryTest.php
  tests/Models/UserTest.php
Labels: ready-for-review

#400 feat(users): make changes in user create and edit for admin can set a…
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  app/Models/User.php
  resources/views/users/edit_modal.blade.php
  resources/views/users/modal.blade.php
  tests/Controllers/Validations/UserControllerValidationTest.php
Labels: approved-by-vishal, ready-for-review

#402 feat(task-detail): fix dropzon image overlapping issue.
  resources/assets/style/sass/style.scss
  resources/assets/style/sass/task-detail.scss
Labels: ready-for-review

#401 feat(task): if stopwatch runnning than that task can not be complete …
  resources/assets/js/custom.js
  resources/assets/js/task/task.js
  resources/assets/js/time_tracker/time_tracker.js
Labels: ready-for-review
