Repository InfyOmLabs/infy-tracker, pull requests merged in 2019-07, with the labels that each got.

#37 fix(hot fix): remove dashboard
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Auth/VerificationController.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  resources/views/layouts/menu.blade.php
  routes/web.php
Labels: ready-for-review

#36 feat(route): added fallback route for wrong route
  routes/web.php
Labels: ready-for-review

#32 feat(Task): display user avtar in task assignee column of task table
  resources/assets/js/task/task.js
  resources/assets/style/sass/style.scss
Labels: ready-for-review

#33 feat(Task): added all option for task status in task filter drop down
  app/Models/Task.php
  app/Queries/TaskDataTable.php
Labels: ready-for-review

#34 feat(task): make delete timeentry function for task
  resources/assets/js/task/task.js
Labels: ready-for-review

#39 Monika/timetracke 143
  resources/assets/js/task/task.js
  resources/assets/js/task/task_detail.js
  resources/assets/js/users/user.js
Labels: ready-for-review

#35 Dharmesh/dashboard user filter and chart js
  app/Http/Controllers/HomeController.php
  app/Repositories/DashboardRepository.php
  app/helpers.php
  resources/assets/js/dashboard/dashboard.js
  resources/assets/js/dashboard/developers-daily-report.js
  resources/views/dashboard/index.blade.php
  resources/views/layouts/menu.blade.php
  routes/web.php
Labels: ready-for-review

#31 fix(task): removed project column in task datatable and display title…
  app/Http/Controllers/TaskController.php
  app/Models/Task.php
  resources/assets/js/task/task.js
  resources/views/tasks/show.blade.php
  resources/views/tasks/table.blade.php
Labels: ready-for-review

#42 fix(task): TIMETRACK-149 only active task come for time entry
  app/Repositories/TimeEntryRepository.php
Labels: ready-for-review

#41 feat(time entry): solve stopwatch start without entering task
  resources/assets/js/time_tracker/time_tracker.js
Labels: ready-for-review

#40 fix(comment): ask for delete confirm, added edit icon
  resources/assets/js/task/task_detail.js
  resources/views/tasks/show.blade.php
Labels: ready-for-review

#43 feat(task): TIMETRACK-153 added text edit in task create/edit
  app/Repositories/TaskRepository.php
  resources/assets/js/task/task.js
  resources/assets/js/task/task_detail.js
  resources/views/tasks/index.blade.php
  resources/views/tasks/modal.blade.php
  resources/views/tasks/show.blade.php
  resources/views/tasks/task_edit_modal.blade.php
Labels: ready-for-review

#45 Harshad/ TIMETRACK-165 Data table data aliment vertically center
  resources/assets/style/sass/style.scss
Labels: ready-for-review

#44 Harshad/Theme Enhancement and locally setup of core ui
  .gitignore
  package-lock.json
  package.json
  resources/assets/js/custom.js
  resources/assets/style/sass/_variables.scss
  resources/assets/style/sass/style.scss
  resources/views/layouts/app.blade.php
Labels: ready-for-review

#46 feat(task): added tooltip for project assignees
  resources/assets/js/task/task.js
Labels: ready-for-review

#47 feat(client): remove width of website column
  resources/assets/js/clients/client.js
Labels: ready-for-review

#48 fix(timer): fix duplicate entry issue
  resources/assets/js/time_tracker/time_tracker.js
Labels: ready-for-review

#50 Harshad/Added font family cdn
  resources/views/layouts/app.blade.php
Labels: ready-for-review

#52 Chart js tooltip "." issue
  app/Repositories/DashboardRepository.php
  resources/assets/js/dashboard/dashboard.js
  resources/assets/js/dashboard/developers-daily-report.js
Labels: ready-for-review

#54 User Avatar color should be same everytime
  app/Models/User.php
  app/helpers.php
  resources/assets/js/task/task.js
Labels: ready-for-review

#38 Dharmesh/roles and permissions
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Http/Requests/CreateRoleRequest.php
  app/Http/Requests/UpdateRoleRequest.php
  app/Models/Permission.php
  app/Models/Role.php
  app/Models/User.php
  app/Queries/RoleDataTable.php
  app/Repositories/PermissionRepository.php
  app/Repositories/RoleRepository.php
  composer.json
  composer.lock
  config/app.php
  config/auth.php
  config/entrust.php
  database/migrations/2019_07_01_050129_entrust_setup_tables.php
  database/seeds/AssignDefaultRoleToUserSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/DefaultRoleSeeder.php
  database/seeds/PermissionTableSeeder.php
  resources/assets/js/permissions/permission.js
  resources/assets/js/roles/role.js
  resources/assets/js/users/user.js
  resources/assets/style/sass/style.scss
  resources/views/layouts/menu.blade.php
  resources/views/roles/create.blade.php
  resources/views/roles/edit.blade.php
  resources/views/roles/edit_fields.blade.php
  resources/views/roles/fields.blade.php
  resources/views/roles/index.blade.php
  resources/views/roles/table.blade.php
  resources/views/users/edit_modal.blade.php
  resources/views/users/modal.blade.php
  resources/views/users/table.blade.php
  routes/web.php
  webpack.mix.js
Labels: ready-for-review

#51 feat(task): added task status functionality
  app/Http/Controllers/TaskController.php
  app/Models/Task.php
  app/Queries/TaskDataTable.php
  app/Repositories/TaskRepository.php
  resources/assets/js/task/task.js
  resources/assets/js/task/task_detail.js
  resources/assets/style/sass/task-detail.scss
  resources/views/tasks/edit_modal.blade.php
  resources/views/tasks/index.blade.php
  resources/views/tasks/show.blade.php
  resources/views/tasks/table.blade.php
Labels: ready-for-review

#49 Dharmesh/logs time entries
  app/Http/Controllers/TimeEntryController.php
Labels: ready-for-review

#65 fix(task): task detail task status issue solve
  resources/assets/js/task/task_detail.js
Labels: ready-for-review

#63 Apply fixes from StyleCI
  app/Exceptions/ApiOperationFailedException.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateUserProfileRequest.php
  app/Http/Requests/UpdateUserRequest.php
  app/Models/User.php
  app/Traits/ImageTrait.php
  config/filesystems.php
  database/migrations/2019_06_17_112629_add_image_path_column_to_users_table.php
Labels: ready-for-review

#73 feat(report): Dynamic report implemented with new UI
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/ReportController.php
  app/Http/Requests/CreateReportRequest.php
  app/Http/Requests/UpdateReportRequest.php
  app/Models/Report.php
  app/Models/ReportFilter.php
  app/Queries/ReportDataTable.php
  app/Repositories/ProjectRepository.php
  app/Repositories/ReportRepository.php
  app/Repositories/UserRepository.php
  database/migrations/2019_07_06_121218_create_reports_table.php
  database/migrations/2019_07_08_114940_create_table_report_filters.php
  resources/assets/js/report/report.js
  resources/assets/style/sass/report.scss
  resources/assets/style/sass/style.scss
  resources/views/layouts/app.blade.php
  resources/views/reports/create.blade.php
  resources/views/reports/edit.blade.php
  resources/views/reports/fields.blade.php
  resources/views/reports/index.blade.php
  resources/views/reports/report_format.blade.php
  resources/views/reports/show.blade.php
  resources/views/reports/table.blade.php
  routes/web.php
  webpack.mix.js
Labels: ready-for-review

#61 feat(layout): TIMETRACK-160 brand logo override issue solve
  resources/views/layouts/app.blade.php
Labels: ready-for-review

#64 fix(task): solve invalid date issue
  resources/assets/js/task/task.js
Labels: ready-for-review

#66 feat(Task): TIMETRACK-174 make month name in shorten format
  resources/assets/js/custom.js
Labels: ready-for-review

#67 fix(roles): #TIMETRACKE-178 UI and consistency in New/edit role screen
  resources/assets/style/sass/style.scss
  resources/views/roles/edit_fields.blade.php
  resources/views/roles/fields.blade.php
Labels: ready-for-review

#68 Completed task should be selected while edit time entry
  app/Http/Controllers/TimeEntryController.php
  app/Repositories/TimeEntryRepository.php
  resources/assets/js/task/task.js
  resources/assets/js/time_entries/time_entry.js
Labels: ready-for-review

#70 fix(roles): Manage both permission separately in settings
  app/Repositories/TaskRepository.php
  resources/assets/style/sass/style.scss
  resources/views/layouts/menu.blade.php
Labels: ready-for-review

#71 Task attachment code refactored
  .gitignore
  app/Exceptions/ApiOperationFailedException.php
  app/Http/Controllers/TaskController.php
  app/Models/Task.php
  app/Models/TaskAttachment.php
  app/Repositories/TaskRepository.php
  app/Traits/ImageTrait.php
  config/filesystems.php
  resources/assets/js/task/task_detail.js
Labels: ready-for-review

#62 Dharmesh/profile image to logged user
  .env.example
  .gitignore
  app/Exceptions/ApiOperationFailedException.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateUserProfileRequest.php
  app/Models/User.php
  app/Traits/ImageTrait.php
  composer.json
  composer.lock
  config/app.php
  config/filesystems.php
  database/migrations/2019_06_17_112629_add_image_path_column_to_users_table.php
  resources/assets/js/profile/profile.js
  resources/assets/style/sass/style.scss
  resources/views/layouts/app.blade.php
  resources/views/profile/edit_profile.blade.php
  routes/web.php
Labels: update-requested

#80 Display Toaster while create and update record
  resources/assets/js/activity_types/activity.js
  resources/assets/js/clients/client.js
  resources/assets/js/custom.js
  resources/assets/js/projects/project.js
  resources/assets/js/tags/tag.js
  resources/assets/js/task/task.js
  resources/assets/js/users/user.js
Labels: ready-for-review

#90 Tests: Models Integration Testing
  composer.json
  composer.lock
  config/database.php
  database/.gitignore
  database/factories/ProjectFactory.php
  database/factories/TaskFactory.php
  database/testing.sqlite
  phpunit.xml
  tests/Browser/ExampleTest.php
  tests/Browser/Pages/HomePage.php
  tests/Browser/Pages/Page.php
  tests/Browser/console/.gitignore
  tests/Browser/screenshots/.gitignore
  tests/DuskTestCase.php
  tests/Integration/Models/ProjectTest.php
  tests/Integration/Models/TaskTest.php
  tests/Unit/Helpers/HelpersTest.php
Labels: ready-for-review

#83 Harshad/Roles checkbox color changes
  resources/assets/img/blue-custom.png
  resources/assets/js/task/task.js
  resources/assets/style/sass/_variables.scss
  resources/assets/style/sass/style.scss
Labels: ready-for-review

#91 Dharmesh/edit delete to report
  app/Http/Controllers/ReportController.php
  resources/assets/js/report/report.js
  resources/views/reports/index.blade.php
  resources/views/reports/show.blade.php
  resources/views/reports/table.blade.php
Labels: ready-for-review

#87 feat(task): added search by task number
  app/Http/Controllers/TaskController.php
  app/Queries/TaskDataTable.php
Labels: ready-for-review

#85 fixed(task): Tooltip is displaying as sticker
  resources/assets/js/task/task.js
Labels: ready-for-review

#86 fix(modal): Add/Edit Task popup should not close on outside click
  resources/assets/js/custom.js
Labels: ready-for-review

#95 (1) Routes name changed to dashed from camel-case
  resources/views/activity_types/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/menu.blade.php
  resources/views/tasks/index.blade.php
  resources/views/time_entries/index.blade.php
  routes/web.php
Labels: ready-for-review

#82 Chart not rendering properly and wrong time display
  app/Repositories/DashboardRepository.php
  app/helpers.php
  resources/assets/js/dashboard/dashboard.js
  resources/assets/js/dashboard/developers-daily-report.js
Labels: ready-for-review

#96 (2) Routes refactored with model substitute binding method
  app/Exceptions/Handler.php
  app/Http/Controllers/ActivityTypeController.php
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateActivityTypeRequest.php
  app/Http/Requests/UpdateClientRequest.php
  app/Http/Requests/UpdateUserRequest.php
  app/Repositories/UserRepository.php
  resources/assets/js/profile/profile.js
  resources/assets/js/users/user.js
  resources/views/profile/edit_profile.blade.php
  routes/web.php
Labels: ready-for-review

#98 (3) Routes refactored with model substitute binding
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/TagController.php
  app/Http/Controllers/TaskController.php
  app/Http/Requests/UpdateProjectRequest.php
  app/Http/Requests/UpdateTagRequest.php
  resources/assets/js/task/task_detail.js
  resources/views/tasks/show.blade.php
  routes/web.php
Labels: ready-for-review

#93 Task/TimeEntry Scope tests added
  app/Http/Controllers/TaskController.php
  app/Http/Controllers/TimeEntryController.php
  app/Models/Task.php
  app/Models/TimeEntry.php
  app/Queries/TaskDataTable.php
  app/Repositories/DashboardRepository.php
  app/Repositories/TaskRepository.php
  app/Repositories/TimeEntryRepository.php
  database/factories/ActivityTypeFactory.php
  database/factories/TimeEntryFactory.php
  database/migrations/2019_06_21_120121_migrate_value_of_task_number_in_tasks_table.php
  tests/Integration/Models/TaskTest.php
  tests/Integration/Models/TimeEntryTest.php
Labels: ready-for-review

#107 feat(reports): percentage support added into report
  .gitignore
  app/Http/Controllers/ReportController.php
  app/Repositories/ReportRepository.php
  resources/views/reports/report_format.blade.php
Labels: ready-for-review

#100 (4) Routes refactored with model substitute binding method
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/TimeEntryController.php
  app/Http/Requests/UpdateRoleRequest.php
  resources/assets/js/task/task_detail.js
  resources/assets/js/time_entries/time_entry.js
  resources/views/tasks/index.blade.php
  resources/views/time_entries/index.blade.php
  routes/web.php
Labels: ready-for-review

#105 Dharmesh/timetracke 177
  app/Http/Controllers/HomeController.php
  app/Repositories/DashboardRepository.php
  app/helpers.php
  resources/views/dashboard/index.blade.php
Labels: ready-for-review

#104 (5) Code refactored
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ProjectController.php
  app/Repositories/ReportRepository.php
  resources/assets/js/report/report.js
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: ready-for-review

#111 Composer updated
  composer.lock
Labels: ready-for-review

#112 fix(dashboard) : remove next week option from dashboard
  resources/assets/js/dashboard/dashboard.js
Labels: ready-for-review

#113 fix(time-entry): make start time and end time required into time entry
  resources/assets/js/time_entries/time_entry.js
  resources/views/time_entries/edit_modal.blade.php
  resources/views/time_entries/modal.blade.php
Labels: ready-for-review

#116 #20 future date is not displaying while generate report
  resources/assets/js/report/report.js
Labels: ready-for-review

#114 Reports edit/delete buttons fixed
  resources/views/reports/table.blade.php
Labels: ready-for-review

#108 Report filters scopes + tests added
  app/Models/ReportFilter.php
  app/Repositories/ReportRepository.php
  database/factories/ReportFactory.php
  database/factories/ReportFilterFactory.php
  tests/Integration/Models/ReportFilterTest.php
Labels: ready-for-review

#117 Harshad/Change of data table loader
  resources/assets/js/custom.js
  resources/assets/style/sass/style.scss
Labels: ready-for-review

#121 feat(report): change report list to report table and created by added
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/TaskController.php
  app/Models/Report.php
  app/Queries/ReportDataTable.php
  app/Repositories/TaskRepository.php
  resources/assets/js/report/report.js
  resources/assets/style/sass/report.scss
  resources/views/layouts/app.blade.php
  resources/views/reports/index.blade.php
  resources/views/reports/table.blade.php
Labels: ready-for-review

#120 Task details screen changes
  app/Models/Comment.php
  resources/assets/js/task/task_detail.js
  resources/views/tasks/show.blade.php
Labels: ready-for-review

#118 Task Assignee render from its project assignee
  app/Models/Project.php
  database/migrations/2019_07_19_055226_populate_project_users_table.php
  resources/assets/js/task/task.js
  resources/views/tasks/edit_modal.blade.php
  resources/views/tasks/modal.blade.php
Labels: ready-for-review

#122 New Release v 1.5.1-alpha
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/TaskController.php
  app/Models/Comment.php
  app/Models/Project.php
  app/Models/Report.php
  app/Models/ReportFilter.php
  app/Queries/ReportDataTable.php
  app/Repositories/ProjectRepository.php
  app/Repositories/ReportRepository.php
  app/Repositories/TaskRepository.php
  composer.json
  composer.lock
  database/factories/ReportFactory.php
  database/factories/ReportFilterFactory.php
  database/migrations/2019_07_19_055226_populate_project_users_table.php
  resources/assets/js/custom.js
  resources/assets/js/dashboard/dashboard.js
  resources/assets/js/report/report.js
  resources/assets/js/task/task.js
  resources/assets/js/task/task_detail.js
  resources/assets/js/time_entries/time_entry.js
  resources/assets/style/sass/report.scss
  resources/assets/style/sass/style.scss
  resources/views/auth/passwords/email.blade.php
  resources/views/layouts/app.blade.php
  resources/views/reports/index.blade.php
  resources/views/reports/show.blade.php
  resources/views/reports/table.blade.php
  resources/views/tasks/edit_modal.blade.php
  resources/views/tasks/modal.blade.php
  resources/views/tasks/show.blade.php
  resources/views/time_entries/edit_modal.blade.php
  resources/views/time_entries/modal.blade.php
  tests/Integration/Models/ReportFilterTest.php
Labels: ready-for-review

#125 Revoke tracker popup on new task/projects create/update/delete
  resources/assets/js/custom.js
  resources/assets/js/projects/project.js
  resources/assets/js/task/task.js
  resources/assets/js/time_tracker/time_tracker.js
Labels: ready-for-review

#123 Start and end time validations into time entry
  app/Http/Controllers/TimeEntryController.php
  app/Repositories/TaskRepository.php
  resources/assets/js/time_entries/time_entry.js
Labels: ready-for-review

#129 #47 chart title changes
  app/Http/Controllers/HomeController.php
  resources/views/dashboard/index.blade.php
Labels: ready-for-review

#127 Report screen fixes
  app/Http/Controllers/ReportController.php
  app/Models/Report.php
  app/Queries/ReportDataTable.php
  resources/assets/js/report/report.js
  resources/assets/style/sass/report.scss
  resources/views/reports/create.blade.php
  resources/views/reports/edit.blade.php
  resources/views/reports/index.blade.php
  resources/views/reports/report_format.blade.php
  resources/views/reports/table.blade.php
Labels: updates-requested

#131 fix formating code
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/TaskController.php
  app/Http/Controllers/TimeEntryController.php
  app/Http/Controllers/UserController.php
  app/Repositories/ProjectRepository.php
  app/Repositories/TaskRepository.php
  app/Repositories/TimeEntryRepository.php
  app/Repositories/UserRepository.php
Labels: ready-for-review

#133 1) Controllers validations test
  database/testing.sqlite
  phpunit.xml
  tests/Controllers/Validations/ActivityTypeControllerValidationTest.php
  tests/TestCase.php
Labels: ready-for-review

#134 (2) Repositories test
  phpunit.xml
  tests/Repositories/ActivityTypeRepositoryTest.php
Labels: ready-for-review

#136 Add Default activity type seeder
  app/Models/ActivityType.php
  database/seeds/DatabaseSeeder.php
  database/seeds/DefaultActivityTypeSeeder.php
Labels: ready-for-review

#146 (2) Client repository tests added
  tests/Repositories/ClientRepositoryTest.php
Labels: ready-for-review

#139 (1) Client Controller tests
  database/factories/ClientFactory.php
  tests/Controllers/Validations/ClientControllerValidationTest.php
  tests/Repositories/ClientRepositoryTest.php
Labels: ready-for-review

#144 (3) Project controller validations tests added
  database/factories/ProjectFactory.php
  tests/Controllers/Validations/ProjectControllerValidationTest.php
Labels: ready-for-review

#149 (4) Project repository test
  tests/Repositories/ProjectRepositoryTest.php
Labels: ready-for-review

#138 (5) test cases for validate task controller API
  tests/Controllers/Validations/ClientControllerValidationTest.php
  tests/Controllers/Validations/TaskControllerValidationTest.php
Labels: ready-for-review

#151 (6) Time Entry controller validations added
  app/Http/Controllers/TimeEntryController.php
  app/Http/Requests/CreateTimeEntryRequest.php
  app/Http/Requests/UpdateTimeEntryRequest.php
  app/Models/TimeEntry.php
  tests/Controllers/Validations/TimeEntryControllerValidationTest.php
Labels: ready-for-review

#162 Time Entry + Task Screen permissions fixes
  app/Http/Controllers/TimeEntryController.php
  app/Queries/TimeEntryDataTable.php
  resources/assets/js/task/task.js
  resources/assets/js/time_entries/time_entry.js
  resources/views/layouts/app.blade.php
  resources/views/layouts/menu.blade.php
  resources/views/tasks/index.blade.php
  resources/views/time_entries/index.blade.php
  routes/web.php
Labels: ready-for-review

#158 test cases for permissions list
  database/factories/PermissionFactory.php
  tests/Repositories/PermissionRepositoryTest.php
Labels: ready-for-review

#156 8) user repository test cases
  database/factories/TagFactory.php
  tests/Repositories/TagRepositoryTest.php
  tests/Repositories/UserRepositoryTest.php
Labels: ready-for-review

#160 test cases for roles repository
  database/factories/RoleFactory.php
  tests/Repositories/RoleRepositoryTest.php
Labels: ready-for-review

#166 Time entry repository test cases added
  tests/Repositories/TimeEntryRepositoryTest.php
  tests/TestCase.php
Labels: ready-for-review

#170 test cases for validate tag controller API
  tests/Controllers/Validations/TagControllerValidationTest.php
Labels: approved-by-vishal, ready-for-review

#173 Comment controller validations tests added
  app/Http/Controllers/CommentController.php
  database/factories/CommentFactory.php
  tests/Controllers/Validations/CommentControllerValidationTest.php
  tests/TestCase.php
Labels: ready-for-review

#176 test case for time entry repo
  tests/Repositories/TimeEntryRepositoryTest.php
Labels: approved-by-vishal, ready-for-review

#163 1) test cases for task repo
  app/Repositories/TaskRepository.php
  database/factories/TagFactory.php
  database/factories/TaskFactory.php
  tests/Repositories/TaskRepositoryTest.php
  tests/TestCase.php
Labels: approved-by-vishal, ready-for-review

#168 3) test cases for report repo
  app/Repositories/ReportRepository.php
  tests/Repositories/ReportRepositoryTest.php
Labels: approved-by-vishal, ready-for-review

#175 test cases for report controller validation API
  tests/Controllers/Validations/ReportControllerValidationTest.php
Labels: approved-by-vishal, ready-for-review

#172 test cases for validate user controller API
  tests/Controllers/Validations/UserControllerValidationTest.php
Labels: approved-by-vishal, ready-for-review

#178 test cases for validate role controller API
  tests/Controllers/Validations/RoleControllerValidationTest.php
Labels: approved-by-vishal, ready-for-review
